version: '3'
services:
    web:
        image: gabrieliroldao/number_to_word:1.0.0
        ports:
            - "5000:5000"
        volumes:
            - ./logs_api:/app/logs
        command: bash -c "python run.py"